### ISSUE TITLE
React router vs xstate router ?

### ISSUE THREAD

**Issue by iangregsondev** [carloslfu/xstate-router#25]
hi,

I found this project via your react router xstate integration repo, it seems to be abandoned. (last commit beginning of 2019)

This is the recommended repository for integrating a router in react using xstate ?

So I presume this replaces react router and just used pure xstate ?

Any help really appreciated

Thanks

**Comment by carloslfu** [comment]
Hi @iangregsondev. I am not actively using/maintaining the react-router XState integration library. So, I recommend you using this library instead. I am actively using and maintaining xstate-router, and, I know there are other people using it too. I will write a note on the other repo to make it clear. Thank you!

**Comment by iangregsondev** [comment]
Cheers.

**Comment by quangv** [comment]
yeah, was unclear the difference was between the two libs as well.
