### ISSUE TITLE
doesn't work with xstate 4.7

### ISSUE THREAD

**Issue by freddydumont** [carloslfu/xstate-router#8]
It seems like the graph methods were moved to a separate repo `@xstate/graph` so this package doesn't work with `xstate@^4.7.0`.

I know it hasn't been updated in a while, but I haven't found another solution for a wizard form.

**Comment by carloslfu** [comment]
Thanks for reporting, @freddydumont.

**Comment by carloslfu** [comment]
Fixed in version [0.4.0](https://www.npmjs.com/package/xstate-router/v/0.4.0).
