### ISSUE TITLE
How to handle intermediate states that shouldn't have a path?

### ISSUE THREAD

**Issue by jaqmol** [carloslfu/xstate-router#9]
In case I want to mix states that should have routes together with states that shouldn't (due to their transitive nature) in the same machine, how do I express this? Just leaving out the `meta: { path: '/whatever }` will drive the router into a runtime-error, setting path to "null" doesn't change the outcome. Thanks in advance.

**Comment by carloslfu** [comment]
I think it's a bug, thanks for reporting @jaqmol. I'll fix it.

**Comment by carloslfu** [comment]
Fixed in `v0.4.1`: https://www.npmjs.com/package/xstate-router/v/0.4.1
